### ISSUE TITLE
Wrap io.aviso.nrepl/pretty-middleware into a Leiningen plugin?

### ISSUE THREAD

**Issue by pmonks** [AvisoNovate/pretty#22]
Adding:

    :repl-options {
        :nrepl-middleware [io.aviso.nrepl/pretty-middleware]
      }

to ~/.lein/profiles.clj results in:

    Error loading io.aviso.nrepl: Could not locate io/aviso/nrepl__init.class or io/aviso/nrepl.clj on classpath:
    Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: io.aviso.nrepl/pretty-middleware in this context, compiling:(/private/var/folders/px/l84gb9tn2dl1kgf1n7jl_2l80000gn/T/form-init7123595979358196767.clj:1:1184)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6567)
        at clojure.lang.Compiler.analyze(Compiler.java:6361)
        at clojure.lang.Compiler.analyze(Compiler.java:6322)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3624)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6562)
        at clojure.lang.Compiler.analyze(Compiler.java:6361)
        at clojure.lang.Compiler.analyze(Compiler.java:6322)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3624)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6562)
        at clojure.lang.Compiler.analyze(Compiler.java:6361)
        at clojure.lang.Compiler.access$100(Compiler.java:37)
        at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:5973)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
        at clojure.lang.Compiler.analyze(Compiler.java:6361)
        at clojure.lang.Compiler.analyze(Compiler.java:6322)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5708)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5139)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3751)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6558)
        at clojure.lang.Compiler.analyze(Compiler.java:6361)
        at clojure.lang.Compiler.eval(Compiler.java:6616)
        at clojure.lang.Compiler.eval(Compiler.java:6609)
        at clojure.lang.Compiler.load(Compiler.java:7064)
        at clojure.lang.Compiler.loadFile(Compiler.java:7020)
        at clojure.main$load_script.invoke(main.clj:294)
        at clojure.main$init_opt.invoke(main.clj:299)
        at clojure.main$initialize.invoke(main.clj:327)
        at clojure.main$null_opt.invoke(main.clj:362)
        at clojure.main$main.doInvoke(main.clj:440)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:419)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)
    Caused by: java.lang.RuntimeException: Unable to resolve var: io.aviso.nrepl/pretty-middleware in this context
        at clojure.lang.Util.runtimeException(Util.java:219)
        at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:650)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
        ... 33 more

when the project itself doesn't have a dependency on io.aviso/pretty.  While I could add that dependency to my ~/.lein/profiles.clj, I'd rather not as that makes io.aviso/pretty a global dependency in all of my projects, whether they use it or not.

Perhaps this part of io.aviso/pretty could be wrapped into a leiningen plugin?

**Comment by hlship** [comment]
I understand that there is a plugin that wraps Pretty and several other libraries now.

**Comment by hlship** [comment]
Fixed in 35d049aca2233304db594b414471268451fd5e8a

Not a perfect fix, perhaps we'll get some help to make it work well with `lein run` as well as `lein repl`.
