### ISSUE TITLE
cider-jack-in times out during startup

### ISSUE THREAD

**Issue by mcfstr** [AvisoNovate/pretty#33]
## client error
Attempting to jack in via Cider results in a client timeout error:
```
nREPL: Establishing direct connection to localhost:55140 ...
nREPL: Direct connection established
error in process filter: nrepl-send-sync-request: Sync nREPL request timed out (op describe id 3)
error in process filter: Sync nREPL request timed out (op describe id 3)
```

## nRepl server error
`ClassCastException` is thrown when the client attempts to connect to the running nRepl server:
```
Apr 03, 2015 10:08:11 AM clojure.tools.logging$eval847$fn__851 invoke
SEVERE: Unhandled REPL handler exception processing message {:op describe, :id 3}
java.lang.ClassCastException: clojure.lang.PersistentHashMap cannot be cast to java.util.Map$Entry
	at clojure.lang.APersistentMap.cons(APersistentMap.java:42)
	at clojure.lang.RT.conj(RT.java:562)
	at clojure.core$conj.invoke(core.clj:83)
	at clojure.core$merge$fn__4314.invoke(core.clj:2759)
	at clojure.core$reduce1.invoke(core.clj:903)
	at clojure.core$reduce1.invoke(core.clj:894)
	at clojure.core$merge.doInvoke(core.clj:2759)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.trace$wrap_trace$fn__7654.invoke(trace.clj:65)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.format$wrap_format$fn__6913.invoke(format.clj:58)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.macroexpand$wrap_macroexpand$fn__7140.invoke(macroexpand.clj:84)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.apropos$wrap_apropos$fn__1954.invoke(apropos.clj:102)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.info$wrap_info$fn__3690.invoke(info.clj:265)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.ns$wrap_ns$fn__7176.invoke(ns.clj:61)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.debug$wrap_debug$fn__4070.invoke(debug.clj:25)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__1389.invoke(interruptible_eval.clj:213)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.pprint$wrap_pprint$fn__7201.invoke(pprint.clj:27)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at clojure.tools.nrepl.middleware.session$add_stdin$fn__1463.invoke(session.clj:235)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at clojure.tools.nrepl.middleware.load_file$wrap_load_file$fn__1504.invoke(load_file.clj:77)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.complete$wrap_complete$fn__3172.invoke(complete.clj:49)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.resource$wrap_resource$fn__7227.invoke(resource.clj:25)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.classpath$wrap_classpath$fn__2021.invoke(classpath.clj:25)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.inspect$wrap_inspect$fn__7102.invoke(inspect.clj:79)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at clojure.tools.nrepl.middleware.pr_values$pr_values$fn__1324.invoke(pr_values.clj:17)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.stacktrace$wrap_stacktrace$fn__7293.invoke(stacktrace.clj:158)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at cider.nrepl.middleware.test$wrap_test$fn__7387.invoke(test.clj:203)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at clojure.tools.nrepl.middleware.session$session$fn__1453.invoke(session.clj:192)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1144.invoke(middleware.clj:24)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:19)
	at clojure.tools.nrepl.server$handle$fn__1517.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__4145.invoke(core.clj:1910)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hlship** [comment]
I'm afraid I'm a Cursive users, not Emacs/Cider. I'm not sure what to do here at all. Suggestions/patches welcome!

**Comment by hlship** [comment]
I'm afraid I have to close this as I have no actionable items.

**Comment by neverfox** [comment]
Same thing happened to me when I added:

```clojure
:repl-options {:nrepl-middleware [io.aviso.nrepl/pretty-middleware]}
```
to my `profiles.clj`. Not sure if that helps make it actionable.
