### ISSUE TITLE
Unable to parse reasonable exception [0.2.21]

### ISSUE THREAD

**Issue by hlship** [AvisoNovate/pretty#38]
From the wild:

```
java.lang.IllegalArgumentException: No value supplied for key: {:host "example.com"}
	at clojure.lang.PersistentHashMap.create(PersistentHashMap.java:77)
	at riemann.client$tcp_client.doInvoke(client.clj:90)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at example.error_monitor$make_connection.invoke(error_monitor.clj:22)
	at example.error_monitor$make_client.invoke(error_monitor.clj:26)
	at clojure.core$map$fn__4553.invoke(core.clj:2624)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$sort.invoke(core.clj:2981)
	at clojure.core$sort_by.invoke(core.clj:2998)
	at clojure.core$sort_by.invoke(core.clj:2996)
	at example.error_monitor$make_clients.invoke(error_monitor.clj:31)
	at example.error_monitor$report_and_reset.invoke(error_monitor.clj:185)
	at example.error_monitor.main$_main$fn__705.invoke(main.clj:19)
	at example.error_monitor.main$_main.doInvoke(main.clj:16)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at example.error_monitor.main.main(Unknown Source)

```

The "Unknown Source" trips up the parse.

**Comment by hlship** [comment]
Fixed in 7488e609c5e6fc929dbb392dbcac437af2e3b530
